/** Search and detail-page metadata for a published semantic rule. */
export interface RuleEntry {
  id: string;
  plugin: string;
  pluginName: string;
  summary: string;
  explanation: string;
  category: string;
  tags: string[];
  searchTerms: string[];
  packageName: string;
  defaultThreshold?: number;
  minConfidence?: number;
  incorrect: string;
  correct: string;
}

export const rules: RuleEntry[] = [
  {
    id: "api-contracts/no-ambiguous-failure-contracts",
    plugin: "api-contracts",
    pluginName: "API Contracts",
    summary: "Disallow overlapping public failure channels.",
    explanation:
      "Directly exported functions should not mix nullable or sentinel results with thrown errors unless each failure representation has a visibly distinct role.",
    category: "API contracts",
    tags: ["failures", "exports", "return-values"],
    searchTerms: ["ambiguous failure", "sentinel", "nullable", "throw"],
    packageName: "@scruple/api-contracts",
    defaultThreshold: 0.8,
    minConfidence: 0.7,
    incorrect: `export function findUser(id: string) { if (!id) throw new Error("missing"); return db.find(id) ?? null; }`,
    correct: `export function findUser(id: string) { if (!id) return null; return db.find(id) ?? null; }`,
  },
  {
    id: "api-contracts/no-ignored-significant-results",
    plugin: "api-contracts",
    pluginName: "API Contracts",
    summary: "Do not discard meaningful call results.",
    explanation:
      "Use results whose visible contracts communicate success, validation, or partial failure instead of invoking the call only for its side effects.",
    category: "API contracts",
    tags: ["return-values", "validation", "failures"],
    searchTerms: ["ignored result", "discarded result", "success indicator"],
    packageName: "@scruple/api-contracts",
    incorrect: `validateOrder(order); submit(order);`,
    correct: `if (validateOrder(order).ok) submit(order);`,
  },
  {
    id: "api-contracts/no-misleading-function-names",
    plugin: "api-contracts",
    pluginName: "API Contracts",
    summary: "Disallow names that contradict visible behavior.",
    explanation:
      "Named implementation functions should fulfill concrete promises made by their names when their behavior is visible in the same file.",
    category: "API contracts",
    tags: ["naming", "functions", "behavior"],
    searchTerms: ["misleading name", "function contract", "contradictory behavior"],
    packageName: "@scruple/api-contracts",
    defaultThreshold: 0.9,
    minConfidence: 0.7,
    incorrect: `function deleteUser(id: string) { return db.users.find(id); }`,
    correct: `function findUser(id: string) { return db.users.find(id); }`,
  },
  {
    id: "api-contracts/no-misleading-http-status",
    plugin: "api-contracts",
    pluginName: "API Contracts",
    summary: "Disallow statuses that contradict visible outcomes.",
    explanation:
      "Explicit HTTP status exits should agree with the route's visible result while allowing accepted work and deliberate protocol or privacy contracts.",
    category: "HTTP contracts",
    tags: ["http", "status-codes", "routes"],
    searchTerms: ["misleading status", "HTTP response", "status code"],
    packageName: "@scruple/api-contracts",
    defaultThreshold: 0.9,
    minConfidence: 0.75,
    incorrect: `app.post("/users", async (_req, res) => { await createUser(); res.sendStatus(404); });`,
    correct: `app.post("/users", async (_req, res) => { await createUser(); res.sendStatus(201); });`,
  },
  {
    id: "api-contracts/no-side-effects-in-safe-http-methods",
    plugin: "api-contracts",
    pluginName: "API Contracts",
    summary: "Disallow requested mutation through safe HTTP methods.",
    explanation:
      "GET, HEAD, OPTIONS, and TRACE routes should not perform requested domain mutations; incidental logging, metrics, auditing, and cache upkeep are allowed.",
    category: "HTTP contracts",
    tags: ["http", "side-effects", "routes"],
    searchTerms: ["safe method", "GET mutation", "HTTP side effect"],
    packageName: "@scruple/api-contracts",
    defaultThreshold: 0.9,
    minConfidence: 0.75,
    incorrect: `app.get("/users/:id/activate", req => activateUser(req.params.id));`,
    correct: `app.post("/users/:id/activate", req => activateUser(req.params.id));`,
  },
  {
    id: "api-contracts/require-input-validation",
    plugin: "api-contracts",
    pluginName: "API Contracts",
    summary: "Require validation of untrusted boundary input.",
    explanation:
      "Explicit route and raw boundary inputs need runtime validation; type annotations alone do not establish that incoming data is valid.",
    category: "Input validation",
    tags: ["validation", "routes", "untrusted-input"],
    searchTerms: ["input validation", "request body", "webhook", "schema"],
    packageName: "@scruple/api-contracts",
    defaultThreshold: 0.85,
    minConfidence: 0.7,
    incorrect: `app.post("/users", req => createUser(req.body));`,
    correct: `app.post("/users", req => createUser(UserSchema.parse(req.body)));`,
  },
  {
    id: "async/no-async-initialization",
    plugin: "async",
    pluginName: "Async",
    summary: "Disallow async work hidden in initialization.",
    explanation:
      "Constructors should not start asynchronous work before callers have an explicit lifecycle boundary that can observe readiness or failure.",
    category: "Async lifecycle",
    tags: ["constructors", "initialization", "promises"],
    searchTerms: ["async constructor", "hidden initialization", "readiness"],
    packageName: "@scruple/async",
    incorrect: `class Client { constructor() { void this.connect(); } }`,
    correct: `class Client { static async create() { const client = new Client(); await client.connect(); return client; } }`,
  },
  {
    id: "async/no-serial-independent-work",
    plugin: "async",
    pluginName: "Async",
    summary: "Do not run independent awaits in series.",
    explanation:
      "Independent operations that do not rely on ordering, shared state, transactions, locks, or rate limits should begin together.",
    category: "Concurrency",
    tags: ["await", "performance", "parallelism"],
    searchTerms: ["serial await", "independent work", "Promise.all"],
    packageName: "@scruple/async",
    defaultThreshold: 0.9,
    minConfidence: 0.7,
    incorrect: `const user = await getUser(id); const flags = await getFlags(id);`,
    correct: `const [user, flags] = await Promise.all([getUser(id), getFlags(id)]);`,
  },
  {
    id: "async/no-unbounded-concurrency",
    plugin: "async",
    pluginName: "Async",
    summary: "Disallow potentially unbounded promise fan-out.",
    explanation:
      "Promise aggregation over boundary-sized collections should use batching or a concurrency limit; fixed tuples are safe.",
    category: "Concurrency",
    tags: ["promises", "limits", "fan-out"],
    searchTerms: ["unbounded concurrency", "Promise.all", "batching"],
    packageName: "@scruple/async",
    defaultThreshold: 0.9,
    minConfidence: 0.7,
    incorrect: `await Promise.all(req.body.urls.map(fetch));`,
    correct: `await mapWithConcurrency(req.body.urls, 8, fetch);`,
  },
  {
    id: "async/no-unobserved-async-work",
    plugin: "async",
    pluginName: "Async",
    summary: "Do not leave started async work unobserved.",
    explanation:
      "Promise-producing calls should be awaited, returned, chained, aggregated, or explicitly marked as deliberate fire-and-forget work.",
    category: "Async lifecycle",
    tags: ["promises", "errors", "fire-and-forget"],
    searchTerms: ["floating promise", "unobserved work", "discarded promise"],
    packageName: "@scruple/async",
    incorrect: `function save() { persist(); }`,
    correct: `async function save() { await persist(); }`,
  },
  {
    id: "async/require-abort-listener-cleanup",
    plugin: "async",
    pluginName: "Async",
    summary: "Require cleanup of abort listeners.",
    explanation:
      "Abort listeners should be one-shot or visibly removed or disposed so they do not outlive the operation they monitor.",
    category: "Cancellation",
    tags: ["abort-signal", "listeners", "cleanup"],
    searchTerms: ["abort listener", "removeEventListener", "once"],
    packageName: "@scruple/async",
    incorrect: `signal.addEventListener("abort", cancel);`,
    correct: `signal.addEventListener("abort", cancel, { once: true });`,
  },
  {
    id: "async/require-cancellation-propagation",
    plugin: "async",
    pluginName: "Async",
    summary: "Require accepted cancellation to be forwarded.",
    explanation:
      "Functions with an explicit AbortSignal contract should forward that signal, directly or through composition, to platform fetch calls.",
    category: "Cancellation",
    tags: ["abort-signal", "fetch", "propagation"],
    searchTerms: ["cancellation propagation", "AbortSignal", "fetch signal"],
    packageName: "@scruple/async",
    defaultThreshold: 0.9,
    minConfidence: 0.7,
    incorrect: `async function load(signal: AbortSignal) { return fetch("/data"); }`,
    correct: `async function load(signal: AbortSignal) { return fetch("/data", { signal }); }`,
  },
  {
    id: "async/require-race-loser-cleanup",
    plugin: "async",
    pluginName: "Async",
    summary: "Require cleanup of locally owned race losers.",
    explanation:
      "Locally created branches that lose Promise.race or Promise.any need cancellation, settlement observation, or cleanup.",
    category: "Concurrency",
    tags: ["Promise.race", "cancellation", "cleanup"],
    searchTerms: ["race loser", "Promise.any", "abandoned work"],
    packageName: "@scruple/async",
    incorrect: `await Promise.race([fetch(url), delay(1000)]);`,
    correct: `await fetch(url, { signal: AbortSignal.timeout(1000) });`,
  },
  {
    id: "comments/no-change-history-comments",
    plugin: "comments",
    pluginName: "Comments",
    summary: "Disallow obsolete change narration.",
    explanation:
      "Comments should explain current constraints rather than narrate completed changes that belong in version control history.",
    category: "Comment quality",
    tags: ["history", "maintenance", "prose"],
    searchTerms: ["change history", "obsolete comment", "previously"],
    packageName: "@scruple/comments",
    defaultThreshold: 0.95,
    minConfidence: 0.7,
    incorrect: `// Changed this from 3 to 5 last Tuesday.\nconst retries = 5;`,
    correct: `// Five retries cover the provider's longest documented outage window.\nconst retries = 5;`,
  },
  {
    id: "comments/no-commented-out-code",
    plugin: "comments",
    pluginName: "Comments",
    summary: "Disallow disabled executable implementation.",
    explanation:
      "Remove executable code hidden in comments while retaining legitimate examples, pseudocode, patterns, and data.",
    category: "Comment quality",
    tags: ["dead-code", "maintenance", "comments"],
    searchTerms: ["commented out code", "disabled implementation", "dead code"],
    packageName: "@scruple/comments",
    defaultThreshold: 0.95,
    minConfidence: 0.7,
    incorrect: `// await legacySave(record);\nawait save(record);`,
    correct: `await save(record);`,
  },
  {
    id: "comments/no-misleading-comments",
    plugin: "comments",
    pluginName: "Comments",
    summary: "Disallow claims contradicted by visible code.",
    explanation:
      "Concrete comment claims should remain consistent with the current behavior visible next to them.",
    category: "Comment correctness",
    tags: ["accuracy", "maintenance", "behavior"],
    searchTerms: ["misleading comment", "stale comment", "contradiction"],
    packageName: "@scruple/comments",
    defaultThreshold: 0.85,
    minConfidence: 0.7,
    incorrect: `// Cache for one minute.\nconst ttlMs = 3_600_000;`,
    correct: `// Cache for one hour.\nconst ttlMs = 3_600_000;`,
  },
  {
    id: "comments/no-useless-comments",
    plugin: "comments",
    pluginName: "Comments",
    summary: "Disallow comments with no maintenance value.",
    explanation:
      "Ordinary comments should add context instead of restating straightforward code, adding generic headings, or narrating obvious actions.",
    category: "Comment quality",
    tags: ["noise", "maintenance", "restatement"],
    searchTerms: ["useless comment", "obvious comment", "code narration"],
    packageName: "@scruple/comments",
    defaultThreshold: 0.9,
    minConfidence: 0.7,
    incorrect: `// Increment count.\ncount += 1;`,
    correct: `// Include the current attempt in the rate-limit window.\ncount += 1;`,
  },
  {
    id: "comments/prefer-concise-comments",
    plugin: "comments",
    pluginName: "Comments",
    summary: "Prefer useful but concise comment prose.",
    explanation:
      "Long ordinary comments should be reduced when substantially shorter prose preserves their maintenance value.",
    category: "Comment quality",
    tags: ["verbosity", "readability", "prose"],
    searchTerms: ["concise comment", "verbose comment", "minCharacters"],
    packageName: "@scruple/comments",
    defaultThreshold: 0.9,
    minConfidence: 0.65,
    incorrect: `// It is important to note that we intentionally retry only once here because another retry is performed by the queue worker upstream.`,
    correct: `// The queue worker performs the second retry.`,
  },
  {
    id: "comments/require-actionable-deprecations",
    plugin: "comments",
    pluginName: "Comments",
    summary: "Require migration guidance in deprecations.",
    explanation:
      "Deprecated APIs should name a replacement, give concrete migration steps, or explain usefully why no replacement exists.",
    category: "API documentation",
    tags: ["deprecation", "migration", "documentation"],
    searchTerms: ["actionable deprecation", "deprecated", "replacement"],
    packageName: "@scruple/comments",
    defaultThreshold: 0.85,
    minConfidence: 0.7,
    incorrect: `/** @deprecated */\nexport function loadOld() {}`,
    correct: `/** @deprecated Use load() instead. */\nexport function loadOld() {}`,
  },
  {
    id: "comments/require-actionable-todos",
    plugin: "comments",
    pluginName: "Comments",
    summary: "Require actionable TODO, FIXME, and HACK markers.",
    explanation:
      "Task markers need enough context to identify the work, rationale, removal condition, or relevant issue without requiring an owner or date.",
    category: "Comment quality",
    tags: ["todo", "fixme", "maintenance"],
    searchTerms: ["actionable TODO", "FIXME", "HACK", "issue"],
    packageName: "@scruple/comments",
    defaultThreshold: 0.8,
    minConfidence: 0.7,
    incorrect: `// TODO: fix this`,
    correct: `// TODO: remove fallback after clients migrate to v2 payloads.`,
  },
  {
    id: "comments/require-justified-suppressions",
    plugin: "comments",
    pluginName: "Comments",
    summary: "Require explanations for tool suppressions.",
    explanation:
      "Explicit lint, type-check, coverage, formatter, Semgrep, and Scruple suppressions should state why bypassing the tool is justified.",
    category: "Tooling directives",
    tags: ["suppression", "lint", "justification"],
    searchTerms: ["eslint disable", "ts-ignore", "coverage ignore", "Semgrep"],
    packageName: "@scruple/comments",
    defaultThreshold: 0.85,
    minConfidence: 0.7,
    incorrect: `// eslint-disable-next-line no-console\nconsole.log(value);`,
    correct: `// eslint-disable-next-line no-console -- CLI output is the public interface.\nconsole.log(value);`,
  },
  {
    id: "errors/no-lossy-error-wrapping",
    plugin: "errors",
    pluginName: "Errors",
    summary: "Disallow replacement errors that lose the original cause.",
    explanation:
      "When a catch handler throws a replacement error, preserve the original failure with a structured cause rather than discarding it.",
    category: "Error handling",
    tags: ["cause", "wrapping", "exceptions"],
    searchTerms: ["lossy wrapping", "error cause", "replacement error"],
    packageName: "@scruple/errors",
    incorrect: `try { await load(); } catch { throw new Error("Load failed"); }`,
    correct: `try { await load(); } catch (cause) { throw new Error("Load failed", { cause }); }`,
  },
  {
    id: "errors/no-message-based-error-dispatch",
    plugin: "errors",
    pluginName: "Errors",
    summary: "Disallow control flow coupled to exception prose.",
    explanation:
      "Branch on stable structured discriminators instead of reading a caught error's human-oriented message to classify failures.",
    category: "Error handling",
    tags: ["messages", "dispatch", "exceptions"],
    searchTerms: ["error message matching", "exception prose", "error code"],
    packageName: "@scruple/errors",
    incorrect: `catch (error) { if (error.message.includes("missing")) return null; throw error; }`,
    correct: `catch (error) { if (error instanceof NotFoundError) return null; throw error; }`,
  },
  {
    id: "errors/no-swallowed-errors",
    plugin: "errors",
    pluginName: "Errors",
    summary: "Disallow silently suppressed unexpected failures.",
    explanation:
      "Catch handlers should propagate or observably report unexpected errors, while intentional recovery and expected-exception fallbacks remain valid.",
    category: "Error handling",
    tags: ["catch", "propagation", "reporting"],
    searchTerms: ["swallowed error", "empty catch", "silent failure"],
    packageName: "@scruple/errors",
    defaultThreshold: 0.9,
    minConfidence: 0.7,
    incorrect: `try { await publish(); } catch { return false; }`,
    correct: `try { await publish(); } catch (error) { logger.error({ error }, "Publish failed"); throw error; }`,
  },
  {
    id: "errors/no-useless-catch-boundaries",
    plugin: "errors",
    pluginName: "Errors",
    summary: "Disallow catch handlers that add no behavior.",
    explanation:
      "Remove catch boundaries that merely rethrow the same error without recovery, cleanup, reporting, translation, or context.",
    category: "Error handling",
    tags: ["catch", "rethrow", "control-flow"],
    searchTerms: ["useless catch", "redundant catch", "direct rethrow"],
    packageName: "@scruple/errors",
    incorrect: `try { return await load(); } catch (error) { throw error; }`,
    correct: `return await load();`,
  },
  {
    id: "observability/no-duplicate-error-reporting",
    plugin: "observability",
    pluginName: "Observability",
    summary: "Do not report the same caught failure twice.",
    explanation:
      "A catch handler should not send multiple recognized reports for the same exception unless a visible policy intentionally requires dual emission.",
    category: "Error telemetry",
    tags: ["logging", "exceptions", "duplicates"],
    searchTerms: ["duplicate reporting", "double log", "captureException"],
    packageName: "@scruple/observability",
    minConfidence: 0.7,
    incorrect: `catch (error) { logger.error(error); telemetry.captureException(error); }`,
    correct: `catch (error) { telemetry.captureException(error); }`,
  },
  {
    id: "observability/no-sensitive-logs",
    plugin: "observability",
    pluginName: "Observability",
    summary: "Disallow sensitive values emitted without redaction.",
    explanation:
      "Detected log and telemetry calls must mask, allowlist, hash for disclosure control, or redact visibly sensitive emitted values.",
    category: "Data protection",
    tags: ["logging", "privacy", "redaction"],
    searchTerms: ["sensitive logs", "password", "token", "PII"],
    packageName: "@scruple/observability",
    defaultThreshold: 0.9,
    minConfidence: 0.7,
    incorrect: `logger.info({ email, password }, "Login attempt");`,
    correct: `logger.info({ emailHash: hash(email) }, "Login attempt");`,
  },
  {
    id: "observability/no-unactionable-errors",
    plugin: "observability",
    pluginName: "Observability",
    summary: "Require operation and failure evidence in error events.",
    explanation:
      "Error and fatal logs and exception telemetry should identify the failed operation and preserve useful evidence about the failure.",
    category: "Error telemetry",
    tags: ["logging", "errors", "diagnostics"],
    searchTerms: ["unactionable error", "error context", "failure evidence"],
    packageName: "@scruple/observability",
    defaultThreshold: 0.85,
    minConfidence: 0.7,
    incorrect: `logger.error("Something failed");`,
    correct: `logger.error({ error, orderId }, "Submitting order failed");`,
  },
  {
    id: "observability/require-operation-context",
    plugin: "observability",
    pluginName: "Observability",
    summary: "Require a stable operation identity in events.",
    explanation:
      "Log and telemetry events should use a specific message or structured field to name the operation; IDs and status alone are insufficient.",
    category: "Telemetry context",
    tags: ["logging", "operations", "structured-data"],
    searchTerms: ["operation context", "event identity", "structured logging"],
    packageName: "@scruple/observability",
    defaultThreshold: 0.8,
    minConfidence: 0.7,
    incorrect: `logger.info({ orderId, status });`,
    correct: `logger.info({ operation: "order.submit", orderId, status });`,
  },
  {
    id: "observability/require-stable-telemetry-names",
    plugin: "observability",
    pluginName: "Observability",
    summary: "Require stable event, span, and metric names.",
    explanation:
      "Telemetry names should be stable literals or visibly bounded templates rather than dynamic values that create unbounded cardinality.",
    category: "Telemetry cardinality",
    tags: ["metrics", "spans", "cardinality"],
    searchTerms: ["dynamic metric name", "stable telemetry", "high cardinality"],
    packageName: "@scruple/observability",
    minConfidence: 0.7,
    incorrect: "metrics.increment(`request.${userId}`);",
    correct: `metrics.increment("request", { userId });`,
  },
  {
    id: "relational-databases/no-query-in-loop",
    plugin: "relational-databases",
    pluginName: "Relational Databases",
    summary: "Disallow per-item relational queries.",
    explanation:
      "Queries inside loops and collection callbacks should be batched or expressed set-wise when they depend on each item.",
    category: "Database performance",
    tags: ["sql", "loops", "batching"],
    searchTerms: ["query in loop", "N+1", "batch query"],
    packageName: "@scruple/relational-databases",
    incorrect: `const users = await Promise.all(ids.map(id => db.user.findUnique({ where: { id } })));`,
    correct: `const users = await db.user.findMany({ where: { id: { in: ids } } });`,
  },
  {
    id: "relational-databases/prefer-database-join",
    plugin: "relational-databases",
    pluginName: "Relational Databases",
    summary: "Prefer joining related query results in the database.",
    explanation:
      "Use a join, relation include, aggregation, subquery, or filtered query when it can replace combining multiple relational query results in memory.",
    category: "Database performance",
    tags: ["sql", "joins", "queries"],
    searchTerms: ["database join", "in-memory join", "relation include"],
    packageName: "@scruple/relational-databases",
    defaultThreshold: 0.85,
    minConfidence: 0.7,
    incorrect: `const users = await db.user.findMany(); const teams = await db.team.findMany(); return users.map(u => ({ ...u, team: teams.find(t => t.id === u.teamId) }));`,
    correct: `return db.user.findMany({ include: { team: true } });`,
  },
  {
    id: "relational-databases/require-deterministic-pagination-order",
    plugin: "relational-databases",
    pluginName: "Relational Databases",
    summary: "Require visible ordering for pagination.",
    explanation:
      "LIMIT/OFFSET and skip/take pagination need a deterministic ordering contract so records do not drift unpredictably between pages.",
    category: "Database correctness",
    tags: ["pagination", "ordering", "queries"],
    searchTerms: ["deterministic pagination", "ORDER BY", "limit offset"],
    packageName: "@scruple/relational-databases",
    incorrect: `db.user.findMany({ skip: page * 20, take: 20 });`,
    correct: `db.user.findMany({ orderBy: { id: "asc" }, skip: page * 20, take: 20 });`,
  },
  {
    id: "relational-databases/require-transaction-scoped-client",
    plugin: "relational-databases",
    pluginName: "Relational Databases",
    summary: "Require transaction-scoped database clients.",
    explanation:
      "Work inside callback transactions and manual BEGIN flows should use the transaction-scoped client rather than a global client or pool.",
    category: "Database correctness",
    tags: ["transactions", "clients", "atomicity"],
    searchTerms: ["transaction client", "global client", "transaction scope"],
    packageName: "@scruple/relational-databases",
    incorrect: `db.transaction(async tx => { await db.account.update(data); });`,
    correct: `db.transaction(async tx => { await tx.account.update(data); });`,
  },
  {
    id: "resources/no-leaked-resources",
    plugin: "resources",
    pluginName: "Resources",
    summary: "Disallow owned resources left unreleased.",
    explanation:
      "Functions should release acquired files, streams, sockets, connections, subscriptions, watchers, locks, transactions, and handles or visibly transfer ownership.",
    category: "Resource lifecycle",
    tags: ["cleanup", "ownership", "handles"],
    searchTerms: ["resource leak", "close", "dispose", "ownership transfer"],
    packageName: "@scruple/resources",
    defaultThreshold: 0.65,
    minConfidence: 0.5,
    incorrect: `async function read() { const file = await open(path); return file.read(); }`,
    correct: `async function read() { await using file = await open(path); return file.read(); }`,
  },
  {
    id: "resources/require-bounded-retries",
    plugin: "resources",
    pluginName: "Resources",
    summary: "Require a finite bound on retry behavior.",
    explanation:
      "Retries need a finite attempt count, elapsed-time limit, or deadline; cancellation alone does not guarantee a bound.",
    category: "Retries",
    tags: ["retry", "limits", "reliability"],
    searchTerms: ["bounded retries", "max attempts", "deadline"],
    packageName: "@scruple/resources",
    defaultThreshold: 0.9,
    minConfidence: 0.7,
    incorrect: `while (true) { try { return await request(); } catch {} }`,
    correct: `for (let attempt = 0; attempt < 3; attempt++) { try { return await request(); } catch {} }`,
  },
  {
    id: "resources/require-cleanup-on-failure",
    plugin: "resources",
    pluginName: "Resources",
    summary: "Require cleanup that is safe on failure.",
    explanation:
      "Cleanup must run when intervening work fails, using managed lifetimes, finally blocks, scoped helpers, or ownership transfer.",
    category: "Resource lifecycle",
    tags: ["cleanup", "exceptions", "finally"],
    searchTerms: ["cleanup on failure", "finally", "using"],
    packageName: "@scruple/resources",
    defaultThreshold: 0.9,
    minConfidence: 0.7,
    incorrect: `const socket = await connect(); await send(socket); socket.close();`,
    correct: `const socket = await connect(); try { await send(socket); } finally { socket.close(); }`,
  },
  {
    id: "resources/require-complete-resource-cleanup",
    plugin: "resources",
    pluginName: "Resources",
    summary: "Require complete cleanup of multiple resources.",
    explanation:
      "When a function acquires multiple resources, all of them must be cleaned up across acquisition, work, and cleanup failure paths.",
    category: "Resource lifecycle",
    tags: ["cleanup", "multiple-resources", "failure-paths"],
    searchTerms: ["partial cleanup", "multiple acquisitions", "resource ownership"],
    packageName: "@scruple/resources",
    incorrect: `const input = await openInput(); const output = await openOutput(); await copy(input, output); output.close();`,
    correct: `await using input = await openInput(); await using output = await openOutput(); await copy(input, output);`,
  },
  {
    id: "resources/require-retry-backoff-with-jitter",
    plugin: "resources",
    pluginName: "Resources",
    summary: "Require retry backoff with jitter.",
    explanation:
      "Retry timing should combine progressively increasing delays with randomization rather than retrying immediately or at a fixed cadence.",
    category: "Retries",
    tags: ["retry", "backoff", "jitter"],
    searchTerms: ["exponential backoff", "retry jitter", "fixed delay"],
    packageName: "@scruple/resources",
    incorrect: `await retry(request, { delayMs: 100 });`,
    correct: `await retry(request, { delay: attempt => 2 ** attempt * 100 + Math.random() * 50 });`,
  },
  {
    id: "resources/require-retry-time-budget",
    plugin: "resources",
    pluginName: "Resources",
    summary: "Require an overall deadline for retry work.",
    explanation:
      "Retries need a total elapsed deadline or inherited deadline-backed context; attempt limits and arbitrary cancellation signals are not total budgets.",
    category: "Retries",
    tags: ["retry", "deadline", "timeout"],
    searchTerms: ["retry budget", "overall timeout", "elapsed deadline"],
    packageName: "@scruple/resources",
    incorrect: `await retry(request, { attempts: 5 });`,
    correct: `await retry(request, { attempts: 5, signal: AbortSignal.timeout(10_000) });`,
  },
  {
    id: "security/no-sensitive-data-exposure",
    plugin: "security",
    pluginName: "Security",
    summary: "Disallow sensitive data sent through output sinks.",
    explanation:
      "Response, render, file-transfer, and redirect sinks should expose only visibly projected, masked, redacted, or sanitized sensitive values.",
    category: "Data protection",
    tags: ["responses", "privacy", "redaction"],
    searchTerms: ["data exposure", "sensitive response", "password", "secret"],
    packageName: "@scruple/security",
    defaultThreshold: 0.9,
    minConfidence: 0.75,
    incorrect: `res.json({ user, passwordHash: user.passwordHash });`,
    correct: `res.json({ user: { id: user.id, name: user.name } });`,
  },
  {
    id: "security/no-unsafe-redirect",
    plugin: "security",
    pluginName: "Security",
    summary: "Disallow request-controlled redirect targets.",
    explanation:
      "Redirect only to fixed local paths or parsed URLs checked against an exact visible origin allowlist.",
    category: "Web security",
    tags: ["redirects", "untrusted-input", "allowlist"],
    searchTerms: ["open redirect", "unsafe redirect", "return URL"],
    packageName: "@scruple/security",
    defaultThreshold: 0.9,
    minConfidence: 0.75,
    incorrect: `res.redirect(req.query.next);`,
    correct: `const next = new URL(req.query.next, appOrigin); res.redirect(next.origin === appOrigin ? next.pathname : "/");`,
  },
  {
    id: "security/no-untrusted-command-execution",
    plugin: "security",
    pluginName: "Security",
    summary: "Disallow request data reaching command or code execution.",
    explanation:
      "Prevent direct same-function flows from request data to shell, command, or dynamic-code execution unless executable and arguments are visibly constrained.",
    category: "Injection",
    tags: ["commands", "shell", "untrusted-input"],
    searchTerms: ["command injection", "shell execution", "eval", "request data"],
    packageName: "@scruple/security",
    defaultThreshold: 0.9,
    minConfidence: 0.75,
    incorrect: "exec(`convert ${req.body.file}`);",
    correct: `execFile("convert", [allowedFiles.get(req.body.file)!], { shell: false });`,
  },
  {
    id: "security/no-untrusted-mass-assignment",
    plugin: "security",
    pluginName: "Security",
    summary: "Disallow wholesale persistence of request objects.",
    explanation:
      "Project or validate an explicit field allowlist before request objects or spreads reach persistence and assignment sinks.",
    category: "Input validation",
    tags: ["mass-assignment", "persistence", "allowlist"],
    searchTerms: ["mass assignment", "request spread", "field projection"],
    packageName: "@scruple/security",
    defaultThreshold: 0.9,
    minConfidence: 0.75,
    incorrect: `await db.user.update({ where: { id }, data: req.body });`,
    correct: `const { displayName } = ProfileSchema.parse(req.body); await db.user.update({ where: { id }, data: { displayName } });`,
  },
  {
    id: "security/no-user-controlled-authorization",
    plugin: "security",
    pluginName: "Security",
    summary: "Disallow authorization based on attacker-controlled claims.",
    explanation:
      "Do not grant access or assign authority from client-controlled roles, permissions, scopes, ownership, tenant, or admin claims without trusted validation.",
    category: "Authorization",
    tags: ["access-control", "untrusted-input", "roles"],
    searchTerms: ["user controlled authorization", "admin claim", "permissions", "tenant"],
    packageName: "@scruple/security",
    defaultThreshold: 0.9,
    minConfidence: 0.75,
    incorrect: `if (req.body.role === "admin") deleteUser(req.params.id);`,
    correct: `if ((await authz.rolesFor(req.user.id)).includes("admin")) deleteUser(req.params.id);`,
  },
  {
    id: "tests/no-fixed-delay-synchronization",
    plugin: "tests",
    pluginName: "Tests",
    summary: "Disallow sleeps used to synchronize tests.",
    explanation:
      "Wait for a condition or use fake clocks instead of sleeps, pauses, waitForTimeout, or direct timers to guess when test work is ready.",
    category: "Test reliability",
    tags: ["timing", "synchronization", "flakiness"],
    searchTerms: ["fixed delay", "sleep", "waitForTimeout", "fake timer"],
    packageName: "@scruple/tests",
    incorrect: `await delay(500); expect(job.done).toBe(true);`,
    correct: `await waitFor(() => expect(job.done).toBe(true));`,
  },
  {
    id: "tests/no-nondeterministic-tests",
    plugin: "tests",
    pluginName: "Tests",
    summary: "Disallow uncontrolled inputs that make tests flaky.",
    explanation:
      "Control direct randomness and wall-clock sources with seeds or fake clocks unless nondeterminism itself is the behavior under test.",
    category: "Test reliability",
    tags: ["randomness", "time", "determinism"],
    searchTerms: [
      "nondeterministic test",
      "Math.random",
      "Date.now",
      "new Date()",
      "DateTime.now",
      "fake clock",
      "injected clock",
    ],
    packageName: "@scruple/tests",
    incorrect: `expect(expiredAt).toBeGreaterThan(Date.now());`,
    correct: `vi.setSystemTime(new Date("2025-01-01")); expect(expiredAt).toBeGreaterThan(Date.now());`,
  },
  {
    id: "tests/no-vacuous-tests",
    plugin: "tests",
    pluginName: "Tests",
    summary: "Disallow tests with no effective behavior verification.",
    explanation:
      "Tests should causally verify claimed behavior with assertions, snapshots, expected failures, or mock interactions rather than merely executing code or asserting tautologies.",
    category: "Test effectiveness",
    tags: ["assertions", "coverage", "behavior"],
    searchTerms: ["vacuous test", "missing assertion", "tautology", "smoke test"],
    packageName: "@scruple/tests",
    defaultThreshold: 0.9,
    minConfidence: 0.7,
    incorrect: `test("adds", () => { add(2, 3); });`,
    correct: `test("adds", () => { expect(add(2, 3)).toBe(5); });`,
  },
  {
    id: "tests/require-specific-error-assertions",
    plugin: "tests",
    pluginName: "Tests",
    summary: "Require assertions that identify the expected failure.",
    explanation:
      "Throw and rejection assertions should check a stable class, code, message contract, or equivalent discriminator unless any failure is intentionally acceptable.",
    category: "Test effectiveness",
    tags: ["errors", "assertions", "specificity"],
    searchTerms: ["specific error", "toThrow", "rejects", "error code"],
    packageName: "@scruple/tests",
    incorrect: `await expect(load("missing")).rejects.toThrow();`,
    correct: `await expect(load("missing")).rejects.toThrow(NotFoundError);`,
  },
];

export const rulesById: ReadonlyMap<string, RuleEntry> = new Map(
  rules.map((rule) => [rule.id, rule]),
);

export const getRule = (id: string): RuleEntry | undefined => rulesById.get(id);
